= Chicago
:hp-alt-title: Where it begins
:hp-tags: Life, UX, 

Before I became a UX person, I spent a good chunk of my life in Chicago, specifically at University of Chicago. But if you ask me to give it a Facebook status, it will for sure be “it’s complicated.”

Chicago is perhaps the most prolific and rewarding intellectual adventure of my life, as well as most socially and mentally messed up one. I gained my academic identity as a computational sociologist along with my obsession with organizational and social network theories. What I lost was my power to go on as an academic. In countless days, when I walked out from Regenstein Library at 3:30 A.M., I took a deep breath of south Chicago’s winter air, and rejoiced that at least I survived the another day. I secretly swore to myself: If I was going to write another word, another single freaking word, I would smash my expensive laptop to the wall, and get a good cry in the library’s hall way. But who I am kidding? There are always more writing and reading, and I will predictably get hyped about new knowledge and my research, my deep deep pride, until 3:30 next morning.

I forget the exact scene where I was brainwashed into the realm of social networks and computational sociology, but I am sure it must be in Professor Padgett’s class — my advisor, a clever brain, that I own much to. I don’t know if it was because of my constant bombardment of questions in his class — he actually more than once asked me to stop — or my effort to explain my concept of non-linearity in aggregated social emotions with my broken English, he did not say no to my request of adviorship. Contrarily, he simply raised his pen and said “Do I sign here?" before I even finished my sentence.

Funny, I think even till now he can not remember my name. “Hey, it’s you”  becomes our version of “hey dude” as the conversation starter. Yet I haven’t regretted any seconds I spent with him. Through him, I have come to realize that I have been always thinking like a complex system scholar. Vocabularies such as “emergence”, “self-organze system” and “complexity" entered my journey and later dominated my time at Chicago. We used to joke about his influence over me was comparable of how he was effected by James March and that he was "sweet-talked" by Harrison White. Of course, I was not even close to what he had accomplished when he encountered his intellectual Muse — in this case Muses— but, I know, my life was forever changed.

Yet, among all great treasures I found at Chicago, I acquired one thing I took sincerely to my heart. Something not only transformed but also transcended me, a scholar or not, that one has to be true to himself.

I recall the moments I wore my gloomy face in his office, being upset by my parents’ marriage issue or simply feeling lost. He pointed out directly that I was not happy, and needed to stop doing whatever “stupid” things that made me feel underachieved. To my surprise, he shared his personal stories about his family and his marriage, which, at the time, sounded like twilight zone of academia to me. He taught me to severe the cord to my pain and focus on whatever I have on hands. Looking back, I was not sure if my eyes turned wet, but I was clear about his message: I need to take care of myself.  

Maybe I was right about his subtext, or maybe I was wrong. After all, it was the first time in my life to exchange deep  feelings with any professors, and I never dreamed it would happen at UChicago. I was always trained to think like a scientist, to separate emotions from facts, and to step back from research subjects. As a social scientist, unfortunately, that “subject” is the life around me. I did not anticipate someday I will give a tight hug to what I have left behind, and that makes me feel alive more than ever. My advisor not only taught me how to think, but also how to live --- as a academic, a professional, or someone who doesn't need to fit into any categories. This, is the ultimately project I have completed at Chicago.

I guess I am truly lucky, for I have studied under a brilliant advisor, and also two incredible recommenders. Professor Edward Laumann, who taught the first-ever sociology class in my life, introduced me to the wonderful world of social networks, organizational studies and sociology of emotions. Whenever I was stuck with my papers, he offered amazingly informative guidance. I even developed an thought that all graduate schools should replace formal classes with office hours and random chat. Talking about out-class interactions, I have to admit I was completely charmed by Professor James Evans for his research, his jokes and his qurky outfit. No one than he has made me think that doing computational sociology is cool. He made me want to talk about my research at dinner table, and brag about it in a birthday party.

Now, I want to stop here. Not only because Starbucks is closing, but also because I don't want to give you an impression that my time at UChicago is everything that defines me. I tell my story because Chicago has an irreplaceable place in my heart, and now, I am ready to move on.
